name: example
description: A new Flutter project.
publish_to: "none"

version: 2.0.0+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^4.0.0-beta6
  flutter:
    sdk: flutter

  find_dropdown:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
